package com.brand.projectd.ui.theme

import androidx.compose.ui.unit.dp


val TRACK_ITEM_SIZE_LARGE = 120.dp
val TRACK_ITEM_PADDING_SMALL = 4.dp
val TRACK_ITEM_PADDING_MEDIUM = 8.dp
val TRACK_ITEM_PADDING_LARGE = 16.dp
val TRACK_ITEM_ELEVATION = 2.dp
val TRACK_ITEM_IMAGE_ROUND_CORNER = 10.dp

val TRACK_DETAILS_PADDING_SMALL = 4.dp
val TRACK_DETAILS_PADDING_MEDIUM = 8.dp
val TRACK_DETAILS_PADDING_LARGE = 16.dp
